# Generated by Django 4.1.13 on 2024-10-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankings',
            name='Delay',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
