# Generated by Django 4.1.13 on 2024-11-11 09:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0003_rename_discription_coursedetails_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipsDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('StudentId', models.CharField(max_length=25, unique=True)),
                ('ProjectName', djongo.models.fields.JSONField(default=list)),
                ('HTMLCode', djongo.models.fields.JSONField(default=dict)),
                ('HTMLScore', djongo.models.fields.JSONField(default=dict)),
                ('CSSCode', djongo.models.fields.JSONField(default=dict)),
                ('CSSScore', djongo.models.fields.JSONField(default=dict)),
                ('JSCode', djongo.models.fields.JSONField(default=dict)),
                ('JSScore', djongo.models.fields.JSONField(default=dict)),
                ('PythonCode', djongo.models.fields.JSONField(default=dict)),
                ('PythonScore', djongo.models.fields.JSONField(default=dict)),
                ('AppPyCode', djongo.models.fields.JSONField(default=dict)),
                ('AppPyScore', djongo.models.fields.JSONField(default=dict)),
                ('DatabaseCode', djongo.models.fields.JSONField(default=dict)),
                ('DatabaseScore', djongo.models.fields.JSONField(default=dict)),
                ('InternshipScores', djongo.models.fields.JSONField(default=dict)),
            ],
        ),
    ]
