# Generated by Django 4.1.13 on 2024-11-11 10:27

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0004_internshipsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipsdetails',
            name='ProjectStatus',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
