# Generated by Django 4.1.13 on 2024-11-12 07:12

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0005_internshipsdetails_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipsdetails',
            name='SubmissionDates',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
