# Generated by Django 4.1.13 on 2024-11-20 10:48

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0006_internshipsdetails_submissiondates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, null=True)),
                ('display_name', models.CharField(max_length=100)),
                ('attended_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'googleMeet_participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Session_Topic', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Start_Time', models.CharField(max_length=20)),
                ('conductedby', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=100)),
                ('meetlink', models.URLField()),
                ('Colleges', djongo.models.fields.JSONField(default=list)),
                ('Branches', djongo.models.fields.JSONField(default=list)),
                ('ended', models.BooleanField(default=False)),
                ('videoLink', models.URLField(default='')),
                ('studentsinvited', djongo.models.fields.JSONField(default=list)),
            ],
            options={
                'db_table': 'meetsessions_session',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='internshipsdetails',
            name='ProjectDateAndTime',
            field=djongo.models.fields.JSONField(default=dict),
        ),
    ]
