# Generated by Django 4.1.13 on 2024-11-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exskilence', '0007_participant_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserCounts',
            fields=[
                ('Sl_id', models.AutoField(primary_key=True, serialize=False)),
                ('StatDateTime', models.DateTimeField()),
                ('ActiveUsers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
